# Generated by Django 5.1.2 on 2024-12-23 06:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0006_alter_featurednews_time_added'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.FloatField()),
                ('original_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField()),
                ('duration', models.DurationField(editable=False)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='main.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_type', models.CharField(help_text="Tipe promosi, misal 'Beli 1 Gratis 1'", max_length=100)),
                ('description', models.TextField(help_text='Deskripsi detail promosi')),
                ('start_date', models.DateTimeField(help_text='Tanggal dan waktu mulai promosi')),
                ('end_date', models.DateTimeField(help_text='Tanggal dan waktu berakhir promosi')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='main.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='UserFavoriteRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='main.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_restaurants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
