# Generated by Django 5.1.2 on 2024-10-24 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions_discounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='discount',
            name='shop_name',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='food_name',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='shop_name',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promotion_type',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='promotions_discounts.shop')),
            ],
        ),
        migrations.AddField(
            model_name='discount',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='promotions_discounts.shop'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='promotions_discounts.shop'),
            preserve_default=False,
        ),
    ]
