# Generated by Django 5.1.2 on 2024-10-25 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions_discounts', '0002_shop_remove_discount_shop_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='discount',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='promotions_discounts.shop'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
