# Generated by Django 5.1.2 on 2024-10-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurednews',
            name='comments',
            field=models.IntegerField(default=60),
        ),
    ]
