# Generated by Django 5.0.7 on 2024-10-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurednews',
            name='comments',
        ),
        migrations.AlterField(
            model_name='featurednews',
            name='grand_image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_news/grand'),
        ),
        migrations.AlterField(
            model_name='featurednews',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_news/icon'),
        ),
    ]
