# Generated by Django 5.0.7 on 2024-10-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_featurednews_comments_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurednews',
            name='comments',
            field=models.IntegerField(default=91),
        ),
    ]
