# Generated by Django 5.1 on 2024-10-27 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_featurednews_comments'),
        ('main', '0002_remove_featurednews_comments_and_more'),
    ]

    operations = [
    ]
