# Generated by Django 5.1.2 on 2024-10-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_featurednews_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurednews',
            name='comments',
            field=models.IntegerField(default=75),
        ),
    ]
