# Generated by Django 5.0.7 on 2024-10-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_featurednews_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurednews',
            name='comments',
            field=models.IntegerField(default=79),
        ),
    ]
