# Generated by Django 5.0.7 on 2024-10-26 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_featurednews_comments'),
        ('main', '0004_alter_featurednews_comments'),
    ]

    operations = [
    ]
