# Generated by Django 5.1.2 on 2024-10-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merge_20241027_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurednews',
            name='comments',
            field=models.IntegerField(default=112),
        ),
        migrations.AlterField(
            model_name='featurednews',
            name='time_added',
            field=models.DateField(default='27/10'),
        ),
    ]
