# Generated by Django 5.1.2 on 2024-10-19 03:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product', models.JSONField(default=[{'description': 'This is product 1', 'id': 1, 'name': 'Product 1', 'price': 1000}, {'description': 'This is product 2', 'id': 2, 'name': 'Product 2', 'price': 2000}, {'description': 'This is product 3', 'id': 3, 'name': 'Product 3', 'price': 3000}, {'description': 'This is product 4', 'id': 4, 'name': 'Product 4', 'price': 4000}, {'description': 'This is product 5', 'id': 5, 'name': 'Product 5', 'price': 5000}])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
